---
title: "Project Proposal - BF"
output: html_document
---

```{r setup, include=FALSE}
```

## Overview

The dataset we will be working on is [Crime Data](https://data.seattle.gov/Public-Safety/Crime-Data/4fs7-3vj5) from the [City of Seattle Open Data portal](https://data.seattle.gov). It records the crimes reported by the public to the Seattle Police Department or detected by officers in different neighborhoods in Seattle over the years. It contains the details about each incident such as occured date, crime subcategory, offence description, occured location, etc.


## Audience

While anybody could get some insights from this report, our intended audience for this report consists of those who are interested in investing in real estate, moving to a new neighborhood or starting businesses, such as running a restaurant. They could get a broad overview of the frequencies of the crimes happened lately in each neighborhood, which would be able to help them make decisions.

## Questions

Some questions this project could answer inculdes:

* What are the frequencies of crimes happened in each neighborhood.
* Which neighborhood has the least crimes happened in the past.
* Which neighborhood has the most crimes happened in the past.
* What is the most common crime incidents (crime subcategory)?
